In [1]:
from pycaret.datasets import get_data
df=get_data(dataset='traffic')

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,1,5545
1,NaN,289.36,0.0,0.0,75,Clouds,0,4516
2,NaN,289.58,0.0,0.0,90,Clouds,0,4767
3,NaN,290.13,0.0,0.0,90,Clouds,0,5026
4,NaN,291.14,0.0,0.0,75,Clouds,0,4918

In [2]:
from pycaret.regression import*

In [3]:
s=setup(df,target='traffic_volume',session_id=123)

In [4]:
best_model=compare_models()

In [5]:
final_model = finalize_model(best_model)
save_model(final_model, 'best_traffic_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['temp', 'rain_1h', 'snow_1h',
                                              'clouds_all', 'Rush Hour'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(inclu...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=-1,
                               num_parallel_tree=None, random_state=123, ...))]),
 'best_traffic_model.pkl')

In [7]:
import pandas as pd

In [8]:
df=pd.read_csv('smsspamcollection.tsv',sep='\t')

In [9]:
df.sample(5)

     label                                            message  length  punct
3237   ham  Aight text me when you're back at mu and I'll ...      92      3
843    ham  Our Prashanthettan's mother passed away last n...      76      3
3521   ham  No it will reach by 9 only. She telling she wi...      70      2
2123   ham                       Do you know when the result.      28      1
738   spam  Hi. Customer Loyalty Offer:The NEW Nokia6650 M...     148      9

In [10]:
from pycaret.classification import*

In [11]:
df=df.drop(columns=['length','punct'])

In [12]:
df.sample(5)

     label                                            message
664    ham        Leave it de:-). Start Prepare for next:-)..
748   spam  U are subscribed to the best Mobile Content Se...
2030   ham             Thanx but my birthday is over already.
1554   ham               Ok how you dear. Did you call chechi
2190   ham  Yup i shd haf ard 10 pages if i add figures......

In [13]:
s=setup(df,target='label',session_id=123)

In [14]:
best=compare_models()

In [15]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [ ]:
predict_model(best)

In [ ]:
new_data=df.copy().drop('label',axis=1)

In [ ]:
prediction=predict_model(best,data=new_data)

In [ ]:
prediction

In [ ]:
save_model(best,'best_pipeline')